#!/usr/bin/env zsh

function _zlint_rule_escaped_single_quotes() {
  local line="$@"

  pcre_compile ''\''[^'\'']+[\\]['\''][^'\'']+'\'''
  pcre_study
  if pcre_match "$line" 2>&1; then
    echo 'Single-quoted string must be closed to escape single quotes, like in '\''This is how it'\''\'\'''\''s done'\'''
    return 1
  fi
}
