#!/usr/bin/env zsh

function _zlint_rule_escaped_commands() {
  local line="$@"

  pcre_compile '^[\\][a-zA-Z-_]+\s?'
  if pcre_match $line; then
    echo 'Prefer `command mycommand` instead of `\mycommand` to override aliases'
    return 1
  fi

  pcre_compile '[^'\'']+\\[^'\'']+'
  if pcre_match $line; then
    echo 'Commands containing backslashes should be single quoted'
    return 1
  fi
}
